"""Build M2 fixtures from frozen independent hand-work and explicit mutations.

No rule interpreter is used to manufacture expected derivations. --check verifies
that every generated byte and the fixture inventory match the committed files.
"""
import argparse
import copy
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INVENTORY = ["a", "b", "p", "f", "v", "t", "d", "s", "x", "a\u0331", "tʰ", "⁵⁵"]


def rule(target, replacement, left=(), right=(), left_edge=False, right_edge=False,
         direction="left-to-right", mode="simultaneous"):
    return dict(target=target, replacement=replacement, left=list(left), right=list(right),
                left_edge=left_edge, right_edge=right_edge, direction=direction, mode=mode)


def package(name, rules, inventory=None):
    return dict(id="synthetic-" + name, version="1.0.0",
                description="Synthetic semantics fixture; no historical reconstruction claim.",
                inventory=list(INVENTORY if inventory is None else inventory),
                initial_stage="s0", final_stage="s" + str(len(rules)),
                laws=[dict(id=f"law-{i + 1}", input_stage=f"s{i}", output_stage=f"s{i + 1}", rule=r)
                      for i, r in enumerate(rules)])


def dossier(name, word, rules, steps, output):
    p = package(name, rules)
    return dict(schema_version="1.0.0", id=name, model=p,
                certificate=dict(package_id=p["id"], package_version=p["version"], input=word,
                                 steps=[dict(rule_id=f"law-{i + 1}", input_stage=f"s{i}",
                                             output_stage=f"s{i + 1}", output=w)
                                        for i, w in enumerate(steps)], output=output))


def encoded(obj):
    return (json.dumps(obj, ensure_ascii=False, indent=2) + "\n").encode()


def generate():
    packet = json.loads((ROOT / "reviews/m2-packet.json").read_text())
    responses = json.loads((ROOT / "reviews/m2-responses.json").read_text())
    answers = {a["id"]: a for a in responses["entries"]}
    files = {}; manifest = []; valid = {}

    def add(name, d, accept, category, rationale, code=None, raw=None):
        path = f"{'valid' if accept else 'invalid'}/{name}.json"
        assert path not in files
        files[path] = raw if raw is not None else encoded(d)
        manifest.append(dict(path=path, accept=accept, code=code,
                             category=category, rationale=rationale))
        if accept:
            valid[name] = d

    for c in packet["cases"]:
        a = answers[c["id"]]
        add(c["id"], dossier(c["id"], c["input"], c["rules"], a["steps"], a["output"]),
            True, "independent-hand-work", a["reasoning"])

    for name, word, rules, steps, output, why in [
        ("identity-package", ["a", "+", "b"], [], [], ["a", "+", "b"], "Empty cascade is identity with no steps."),
        ("only-boundaries", ["+", "+"], [rule(["a"], None)], [["+", "+"]], ["+", "+"], "Boundaries survive deletion rules."),
        ("delete-all", ["a", "a"], [rule(["a"], None, mode="feeding")], [[]], [], "Deleting each original segment produces an empty word."),
        ("multiple-class-members", ["b", "p", "a", "+", "a", "t", "b"],
         [rule(["p", "t"], "s", left=[["a", "b"]], right=["*"])],
         [["b", "s", "a", "+", "a", "s", "b"]], ["b", "s", "a", "+", "a", "s", "b"], "Every matching member of an explicit segment class changes."),
        ("replacement-not-revisited", ["a"], [rule(["a"], "a", mode="feeding")], [["a"]], ["a"], "A self-replacement consumes one original token and terminates.")
    ]:
        add(name, dossier(name, word, rules, steps, output), True, "boundary-contract", why)

    def bad(name, base, code, category, rationale, mutate):
        d = copy.deepcopy(valid[base]); d["id"] = name
        mutate(d)
        add(name, d, False, category, rationale, code)

    def output(d, word):
        d["certificate"]["steps"][-1]["output"] = word
        d["certificate"]["output"] = word

    bad("missing-step", "ordered-cascade", "TRACE_LENGTH", "trace-shape", "A law's complete stage cannot be omitted.", lambda d: d["certificate"]["steps"].pop(0))
    bad("extra-step", "ordered-cascade", "TRACE_LENGTH", "trace-shape", "An extra stage is not licensed.", lambda d: d["certificate"]["steps"].append(copy.deepcopy(d["certificate"]["steps"][-1])))
    bad("omit-unchanged-step", "reversed-cascade", "TRACE_LENGTH", "trace-shape", "A no-change pass still requires a certificate step.", lambda d: d["certificate"]["steps"].pop(0))
    bad("reordered-steps", "ordered-cascade", "RULE_ID", "rule-order", "Certificate order must match named laws.", lambda d: d["certificate"]["steps"].reverse())
    bad("wrong-law-id", "unconditional", "RULE_ID", "rule-order", "A different law identity cannot be substituted.", lambda d: d["certificate"]["steps"][0].update(rule_id="another-law"))
    bad("reused-law-id", "ordered-cascade", "RULE_ID", "rule-order", "Repeated certificate law IDs cannot replace the next law.", lambda d: d["certificate"]["steps"][1].update(rule_id="law-1"))
    bad("wrong-input-stage", "unconditional", "TRACE_STAGE", "stage-identity", "The certificate must name the actual input stage.", lambda d: d["certificate"]["steps"][0].update(input_stage="other"))
    bad("wrong-output-stage", "unconditional", "TRACE_STAGE", "stage-identity", "The certificate must name the actual output stage.", lambda d: d["certificate"]["steps"][0].update(output_stage="other"))
    bad("wrong-final", "ordered-cascade", "FINAL_OUTPUT", "trace-shape", "The final word must equal the final step.", lambda d: d["certificate"].update(output=["x"]))
    bad("corrupt-middle", "ordered-cascade", "STEP_OUTPUT", "trace-shape", "A plausible final word does not excuse an invalid intermediate word.", lambda d: d["certificate"]["steps"][0].update(output=["x", "a"]))
    for name, base, word, category, why in [
        ("skip-all-matches", "unconditional", ["p", "a", "p", "a"], "uniformity", "Matching occurrences must change."),
        ("change-one-occurrence", "unconditional", ["f", "a", "p", "a"], "uniformity", "A rule cannot arbitrarily change only the first of two matches."),
        ("ltr-sim-feeds", "ltr-simultaneous", ["b", "b", "b"], "feeding-vs-simultaneous", "Simultaneous left context cannot see a newly produced b."),
        ("ltr-feeding-frozen", "ltr-feeding", ["b", "b", "a"], "feeding-vs-simultaneous", "Feeding left context sees the produced b."),
        ("rtl-sim-feeds", "rtl-simultaneous", ["b", "b", "b"], "feeding-vs-simultaneous", "Simultaneous right context is original."),
        ("rtl-feeding-frozen", "rtl-feeding", ["a", "b", "b"], "feeding-vs-simultaneous", "Right-to-left feeding sees produced right context."),
        ("deletion-sim-feeds", "deletion-simultaneous", ["b"], "deletion", "Simultaneous deletion cannot expose b for another match."),
        ("deletion-feed-frozen", "deletion-feeding", ["b", "a"], "deletion", "Feeding deletion exposes the preceding b."),
        ("ignore-initial-anchor", "word-initial", ["f", "a", "f"], "context", "An initial-only rule cannot change final p."),
        ("ignore-final-anchor", "word-final-deletion", ["a"], "context", "Final deletion cannot delete initial t."),
        ("wildcard-crosses-boundary", "boundary-blocks-wildcard", ["a", "+", "b", "a"], "boundary", "A segment wildcard cannot match a morpheme boundary."),
        ("erase-morpheme-boundary", "morpheme-context", ["p", "b", "a"], "boundary", "A rule cannot delete a boundary."),
        ("rtl-swaps-word-edges", "rtl-word-initial", ["p", "a", "f"], "direction", "Right-to-left scanning does not exchange original word-initial and word-final conditions."),
        ("unvisited-context-feeds", "unvisited-context", ["b", "p", "p"], "feeding-vs-simultaneous", "Unvisited right context remains original in a left-to-right pass."),
        ("normalize-atomic-token", "unicode-atoms", ["a", "s", "⁵⁵"], "unicode", "A combining-mark atom cannot be silently normalized or stripped."),
        ("feeding-edge-not-exposed", "edge-exposed-by-deletion", ["a", "b"], "deletion", "Feeding deletion exposes the word edge for the next original a.")
    ]:
        bad(name, base, "STEP_OUTPUT", category, why, lambda d, word=word: output(d, word))
    bad("reverse-nearest-first", "two-token-context", "STEP_OUTPUT", "context", "Left context is nearest-first, not left-to-right spelling order.", lambda d: d["model"]["laws"][0]["rule"].update(left=[["p"], ["a"]]))

    def boundary_is_not_edge(d):
        d["certificate"]["input"] = ["+", "p"]
        output(d, ["+", "f"])
    bad("boundary-is-not-word-edge", "word-initial", "STEP_OUTPUT", "boundary", "A morpheme boundary is not a word edge.", boundary_is_not_edge)

    def change_order(d):
        ls = d["model"]["laws"]
        ls[0]["rule"], ls[1]["rule"] = ls[1]["rule"], ls[0]["rule"]
    bad("changed-model-order", "ordered-cascade", "STEP_OUTPUT", "rule-order", "Changing package rule order changes the licensed trace even when labels and stages remain valid.", change_order)

    mutations = [
        ("package-mismatch", "PACKAGE_IDENTITY", lambda d: d["certificate"].update(package_id="different")),
        ("version-mismatch", "PACKAGE_IDENTITY", lambda d: d["certificate"].update(package_version="2.0.0")),
        ("duplicate-inventory", "INVENTORY", lambda d: d["model"]["inventory"].append("a")),
        ("empty-inventory", "INVENTORY", lambda d: d["model"].update(inventory=[])),
        ("empty-symbol", "INVENTORY", lambda d: d["model"]["inventory"].append("")),
        ("whitespace-symbol", "INVENTORY", lambda d: d["model"]["inventory"].append("a b")),
        ("boundary-in-inventory", "INVENTORY", lambda d: d["model"]["inventory"].append("+")),
        ("unknown-target", "TARGET_CLASS", lambda d: d["model"]["laws"][0]["rule"].update(target=["q"])),
        ("empty-target", "TARGET_CLASS", lambda d: d["model"]["laws"][0]["rule"].update(target=[])),
        ("duplicate-target", "TARGET_CLASS", lambda d: d["model"]["laws"][0]["rule"].update(target=["p", "p"])),
        ("unknown-replacement", "REPLACEMENT", lambda d: d["model"]["laws"][0]["rule"].update(replacement="q")),
        ("replace-with-boundary", "REPLACEMENT", lambda d: d["model"]["laws"][0]["rule"].update(replacement="+")),
        ("unknown-context", "CONTEXT_CLASS", lambda d: d["model"]["laws"][0]["rule"].update(left=[["q"]])),
        ("empty-context-class", "CONTEXT_CLASS", lambda d: d["model"]["laws"][0]["rule"].update(left=[[]])),
        ("duplicate-context-class", "CONTEXT_CLASS", lambda d: d["model"]["laws"][0]["rule"].update(right=[["a", "a"]])),
        ("unbounded-left-context", "CONTEXT_BOUND", lambda d: d["model"]["laws"][0]["rule"].update(left=["*", "*", "*"])),
        ("unbounded-right-context", "CONTEXT_BOUND", lambda d: d["model"]["laws"][0]["rule"].update(right=["*", "*", "*"])),
        ("broken-stage-chain", "STAGE_CHAIN", lambda d: d["model"]["laws"][0].update(input_stage="elsewhere")),
        ("wrong-final-stage", "STAGE_CHAIN", lambda d: d["model"].update(final_stage="unreached")),
        ("cyclic-stage-name", "STAGE_ORDER", lambda d: d["model"]["laws"][0].update(output_stage="s0")),
        ("invalid-law-id", "RULE_IDS", lambda d: d["model"]["laws"][0].update(id="bad id")),
        ("unknown-input-segment", "WORD_INVENTORY", lambda d: d["certificate"].update(input=["q"])),
        ("unknown-step-segment", "WORD_INVENTORY", lambda d: d["certificate"]["steps"][0].update(output=["q"])),
        ("unknown-output-segment", "WORD_INVENTORY", lambda d: d["certificate"].update(output=["q"])),
        ("schema-version", "SCHEMA_VERSION", lambda d: d.update(schema_version="9.0.0")),
        ("invalid-dossier-id", "DOSSIER_ID", lambda d: d.update(id="bad id")),
        ("missing-package-version", "PACKAGE_METADATA", lambda d: d["model"].update(version="")),
        ("iterate-to-fixed-point", "JSON_SHAPE", lambda d: d["model"]["laws"][0]["rule"].update(mode="repeat-until-stable")),
        ("whole-word-lookup", "JSON_SHAPE", lambda d: d["model"]["laws"][0]["rule"].update(word_map={"papa": "baba"})),
        ("lexical-exceptions", "JSON_SHAPE", lambda d: d["model"]["laws"][0]["rule"].update(except_ids=["word-1"])),
        ("insertion-operation", "JSON_SHAPE", lambda d: d["model"]["laws"][0]["rule"].update(operation="insert")),
        ("word-replacement", "JSON_SHAPE", lambda d: d["model"]["laws"][0]["rule"].update(replacement=["b", "a"])),
        ("unknown-direction", "JSON_SHAPE", lambda d: d["model"]["laws"][0]["rule"].update(direction="random")),
        ("omit-explicit-replacement", "JSON_SHAPE", lambda d: d["model"]["laws"][0]["rule"].pop("replacement")),
        ("hidden-predicate", "JSON_SHAPE", lambda d: d["model"]["laws"][0]["rule"].update(target={"python": "lambda word: True"})),
    ]
    for name, code, mutate in mutations:
        bad(name, "unconditional", code, "grammar-and-packaging",
            "Reject " + name.replace("-", " ") + " under the explicit rule/package contract.", mutate)
    # Regression for review finding M2-R1: Lean's Char.isWhitespace is not the
    # Unicode White_Space property. Each non-ASCII separator needs its own case.
    for point in [0x00A0, 0x1680, *range(0x2000, 0x200B), 0x2028, 0x2029, 0x202F, 0x205F, 0x3000]:
        bad(f"unicode-whitespace-{point:04x}", "unconditional", "INVENTORY", "unicode-whitespace",
            f"Unicode White_Space U+{point:04X} cannot be an atomic segment symbol.",
            lambda d, point=point: d["model"]["inventory"].append(chr(point)))
    bad("embedded-unicode-whitespace", "unconditional", "INVENTORY", "unicode-whitespace",
        "Whitespace is forbidden inside a segment string, not just as an entire symbol.",
        lambda d: d["model"]["inventory"].append("a\u2028b"))
    bad("duplicate-law-identities", "ordered-cascade", "RULE_IDS", "grammar-and-packaging", "Distinct package laws need unique identities.", lambda d: d["model"]["laws"][1].update(id="law-1"))
    raw = encoded(valid["unconditional"])
    add("duplicate-json-key", None, False, "parser", "Duplicate keys cannot conceal an alternate target or output.", "DUPLICATE_JSON_KEY", raw.replace(b'"schema_version": "1.0.0"', b'"schema_version": "1.0.0", "schema_version": "1.0.0"', 1))
    add("invalid-utf8", None, False, "parser", "Malformed UTF-8 is rejected without replacing bytes.", "UTF8", b'\xff')
    add("invalid-json", None, False, "parser", "Syntactically malformed JSON is rejected.", "JSON_SYNTAX", b'{')
    add("surrogate-escape", None, False, "parser", "Supplementary characters must use literal UTF-8 across both supported Lean parsers.", "UNICODE_ESCAPE", raw.replace(b'Synthetic semantics fixture;', b'\\ud83d\\ude00 Synthetic semantics fixture;', 1))
    files["manifest.json"] = encoded(dict(schema_version="1.0.0", suite="contextual-rules", fixtures=manifest))
    packages = [d["model"] for d in valid.values()]
    return files, encoded(packages), manifest


def main():
    p = argparse.ArgumentParser(description=__doc__); p.add_argument("--check", action="store_true")
    args = p.parse_args(); files, packages, manifest = generate()
    targets = {ROOT / "data/contextual-rules" / name: content for name, content in files.items()}
    targets[ROOT / "data/rule-packages/contextual-examples.json"] = packages
    actual = set((ROOT / "data/contextual-rules").rglob("*.json"))
    expected = {path for path in targets if "contextual-rules" in path.parts}
    assert not actual - expected, f"Unlisted generated fixtures: {actual - expected}"
    for path, content in targets.items():
        if args.check:
            assert path.read_bytes() == content, f"Stale generated artifact: {path.relative_to(ROOT)}"
        else:
            path.parent.mkdir(parents=True, exist_ok=True); path.write_bytes(content)
    print(f"M2 fixtures: {sum(f['accept'] for f in manifest)} valid, {sum(not f['accept'] for f in manifest)} adversarial; {'verified' if args.check else 'generated'}")


if __name__ == "__main__":
    main()
