"""Render the human catalogue, BibTeX and attribution notices from reviewed JSON."""
import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
LICENSE_URLS={
 'CC BY 4.0':'https://creativecommons.org/licenses/by/4.0/',
 'CC BY-NC 4.0':'https://creativecommons.org/licenses/by-nc/4.0/',
 'CC BY-NC-ND 4.0':'https://creativecommons.org/licenses/by-nc-nd/4.0/',
 'CC BY-ND 2.0':'https://creativecommons.org/licenses/by-nd/2.0/',
 'CC BY-NC-SA 3.0':'https://creativecommons.org/licenses/by-nc-sa/3.0/',
 'CC BY-NC (version unspecified in PDF)':'https://www.elra.info/',
 'STEDT academic noncommercial unmodified redistribution':'https://stedt.berkeley.edu/pubs.html',
}


def tex(s):
    return str(s).replace('\\','\\textbackslash{}').replace('&','\\&').replace('%','\\%').replace('_','\\_').replace('#','\\#')


def main():
    sources=json.loads((ROOT/'bibliography/sources.json').read_text())
    downloads={x['id']:x for x in json.loads((ROOT/'bibliography/downloads.json').read_text())}
    notes={x['id']:x for x in json.loads((ROOT/'bibliography/reading-notes.json').read_text())}
    total=sum(d['status']=='downloaded' for d in downloads.values())
    qualifying=sum(s['qualifies_for_download_floor'] and downloads[s['id']]['status']=='downloaded' for s in sources)
    public=sum(s.get('redistribute',False) and downloads[s['id']]['status']=='downloaded' for s in sources)
    lines=['# Annotated research catalogue','',f'{len(sources)} references; **{total} retained PDFs, {qualifying} qualifying distinct works**, and {public} PDFs included in the public repository. The remaining successful downloads are retained locally and recoverable from the source URLs where access persists.','',
           'The conservative floor excludes proposals, reviews/replies and a separately downloaded chapter already contained in a downloaded book. Reading scope is stated for every entry. “Focused excerpts” means selected substantive passages, not every page. “Screened excerpts” means opening/abstract material and selected closing passages where available. PDF page numbers refer to the downloaded file, including covers. Findings paraphrase the sources; formalization uses and cautions are this study’s analysis.','',
           'Machine-readable files: [sources](sources.json), [downloads and checksums](downloads.json), [reading notes](reading-notes.json), [BibTeX](references.bib). See [acquisition methodology](../docs/06-research-method.md) and [audit](../reports/library-audit.json).','',
           '| ID | Year | Work | Areas | Acquisition |', '|---|---:|---|---|---|']
    for s in sources:
        d=downloads[s['id']]
        state=(f'{d["pages"]} pages; '+('public PDF' if s.get('redistribute') else 'local PDF')) if d['status']=='downloaded' else 'access gap'
        lines.append(f'| [{s["id"]}](#{s["id"].lower()}) | {s["year"]} | {s["title"].replace("|","/")} | {", ".join(s["areas"])} | {state} |')
    bib=[]
    notice=['# Third-party publication notices','',
            'The PDFs in `library/open/` are unmodified third-party publications, reproduced for noncommercial research under the source-specific permissions below. They are **not** covered by the repository’s MIT license. Copyright and other notices remain in the PDFs. Several works prohibit commercial use or derivatives; the STEDT monographs also require unmodified, no-charge academic distribution.','',
            'For the four ELRA 2020 PDFs, the printed notice specifies CC-BY-NC without a version; this catalogue does not assign a version that the notice does not state. The source PDF retains the original notice.','',
            'Other publications remain in the ignored local library. Public accessibility alone is not treated as permission to republish. This file is generated by `scripts/build_catalogue.py` from the reviewed catalogue.','']
    for s in sources:
        sid=s['id'];d=downloads[sid];n=notes[sid]
        lines.extend(['',f'<a id="{sid.lower()}"></a>',f'## {sid} — {s["title"]}','',f'{"; ".join(s["authors"])} ({s["year"]}). {s["kind"]}. [Source]({s["url"]}) · [Original PDF URL]({s["pdf_url"]})'+(f' · [DOI](https://doi.org/{s["doi"]})' if s.get('doi') else '')])
        if d['status']=='downloaded':
            loc=f'[Public PDF](../{d["path"]})' if s.get('redistribute') else f'Local path: `{d["path"]}` (not in public Git)'
            lines.extend(['',f'{loc}. {d["pages"]} PDF pages; {d["bytes"]:,} bytes. SHA-256: `{d["sha256"]}`.'])
        else:lines.extend(['','**Acquisition gap:** no retained PDF; excluded from the download count. See the ledger for the failed attempt.'])
        lines.extend(['',f'**Reading scope:** {n["reading_level"]}'+(f'; PDF pages {", ".join(map(str,n["pdf_pages_examined"]))}.' if n['pdf_pages_examined'] else '.'),
            '',f'**Finding:** {n["finding"]}',f'**Formalization use:** {n["formalization_use"]}',f'**Boundary:** {n["caution"]}',
            '',f'**Rights:** {s["license"]}.'])
        if s.get('version_note'):lines.extend(['',f'**Version note:** {s["version_note"]}'])
        if s.get('text_quality_note'):lines.extend(['',f'**Extraction:** {s["text_quality_note"]}'])
        if not s['qualifies_for_download_floor']:lines.extend(['',f'**Counting:** {s["count_exclusion"]}.'])
        typ={'book':'book','chapter':'incollection','thesis':'phdthesis'}.get(s['kind'],'misc')
        fields={'title':'{'+tex(s['title'])+'}','author':' and '.join(tex(a) for a in s['authors']),'year':s['year'],'url':s['url']}
        if s.get('doi'):fields['doi']=s['doi']
        fields['note']='Catalogue ID '+sid+'; '+s['kind']+(('; '+s['version_note']) if s.get('version_note') else '')
        if s.get('included_in'):fields['note']+='; also contained in '+s['included_in']
        bib.append('@'+typ+'{'+sid+',\n'+',\n'.join('  '+k+' = {'+v+'}' for k,v in fields.items())+'\n}\n')
        if s.get('redistribute') and d['status']=='downloaded':
            url=LICENSE_URLS[s['license']]
            notice.extend([f'## {sid}','',f'**{s["title"]}** — {"; ".join(s["authors"])} ({s["year"]}).',
                '',f'[Original source]({s["url"]}) · [Original PDF]({s["pdf_url"]}) · [Retained unmodified PDF](../{d["path"]})',
                '',f'License/permission: [{s["license"]}]({url}). Basis: {s["rights_basis"]}.',
                '',f'SHA-256: `{d["sha256"]}`. No changes to the publication.',''])
    (ROOT/'bibliography/README.md').write_text('\n'.join(lines).rstrip()+'\n')
    (ROOT/'bibliography/references.bib').write_text('\n'.join(bib).rstrip()+'\n')
    (ROOT/'library/THIRD_PARTY_NOTICES.md').write_text('\n'.join(notice).rstrip()+'\n')
    print(f'Rendered {len(sources)} annotations and {public} publication notices')


if __name__=='__main__':main()
