import Comparative
import Historical

#print axioms Comparative.run_append
#print axioms Comparative.derives_iff_run
#print axioms Comparative.checkTrace_sound
#print axioms Comparative.checkTrace_complete
#print axioms Comparative.fits_mono
#print axioms Comparative.fits_of_equivalent
#print axioms Comparative.mem_reconstruct_iff
#print axioms Comparative.reconstruction_correct
#print axioms Comparative.reconstruct_mono
#print axioms Comparative.Examples.rule_order_matters
#print axioms Comparative.Examples.valid_certificate
#print axioms Comparative.Examples.corrupted_certificate_rejected
#print axioms Comparative.Examples.missing_step_rejected
#print axioms Comparative.Examples.extra_step_rejected
#print axioms Comparative.Examples.distinct_protoforms
#print axioms Comparative.Examples.merger_ambiguity
#print axioms Comparative.Examples.finite_reconstruction_keeps_ambiguity
#print axioms Comparative.Examples.fits_checker_reflects
#print axioms Comparative.Patterns.compatible_is_not_transitive
#print axioms Comparative.Patterns.missing_is_not_gap
#print axioms Comparative.Patterns.missing_alone_is_not_support
#print axioms Comparative.Patterns.independent_choices_overgenerate

#print axioms Historical.replay_iff_chain
#print axioms Historical.renormalize_preserves_original
#print axioms Historical.renormalize_preserves_choices
#print axioms Historical.missing_ne_gap
#print axioms Historical.cell_json_roundtrip

#print axioms Historical.Rules.emits_iff_outputAt
#print axioms Historical.Rules.scan_eq_iff
#print axioms Historical.Rules.pass_iff_apply
#print axioms Historical.Rules.pass_deterministic
#print axioms Historical.Rules.outputAt_length_le
#print axioms Historical.Rules.scan_length_le
#print axioms Historical.Rules.applyRule_length_le
#print axioms Historical.Rules.morpheme_copied
#print axioms Historical.Certificates.checkTrace_iff
#print axioms Historical.Certificates.checkTrace_sound
#print axioms Historical.Certificates.checkTrace_complete
#print axioms Historical.Certificates.derives_iff_run
#print axioms Historical.Certificates.trace_implies_derives
#print axioms Historical.Certificates.run_append
#print axioms Historical.Certificates.canonical_trace_accepted
#print axioms Historical.Certificates.derivation_iff_certificate
#print axioms Historical.RuleInput.checkDossier_iff

#print axioms Historical.Alignment.removeGaps_iff
#print axioms Historical.Alignment.checkRow_iff
#print axioms Historical.Alignment.accepted_row_recovers
#print axioms Historical.Alignment.missing_is_not_erased
#print axioms Historical.Alignment.missing_row_ne_empty
#print axioms Historical.Alignment.checkAlignment_iff
#print axioms Historical.Alignment.accepted_alignment_preserves_rows
#print axioms Historical.Alignment.accepted_alignment_preserves_absence
#print axioms Historical.Alignment.accepted_alignment_has_material
#print axioms Historical.Correspondence.cellAgrees_iff
#print axioms Historical.Correspondence.sharedSound_iff
#print axioms Historical.Correspondence.noConflict_iff
#print axioms Historical.Correspondence.hasShared_iff
#print axioms Historical.Correspondence.compatible_iff
#print axioms Historical.Correspondence.missing_only_no_support
#print axioms Historical.Correspondence.unknown_only_no_support
#print axioms Historical.Correspondence.gap_only_no_support
#print axioms Historical.Correspondence.mem_distinctUnits
#print axioms Historical.Correspondence.distinctUnits_nodup
#print axioms Historical.Correspondence.mem_supportUnits
#print axioms Historical.Correspondence.checkClique_iff
#print axioms Historical.Correspondence.checkGroup_iff
#print axioms Historical.Correspondence.accepted_group_pairwise
#print axioms Historical.Correspondence.accepted_group_support
#print axioms Historical.Correspondence.checkPartition_iff
#print axioms Historical.Correspondence.accepted_partition_exactly_once
#print axioms Historical.Correspondence.accepted_partition_groups_valid
#print axioms Historical.Correspondence.compatibility_not_transitive
#print axioms Historical.Correspondence.nontransitive_merge_rejected
#print axioms Historical.Correspondence.missing_differs_from_gap
#print axioms Historical.Correspondence.disjoint_observations_not_support
#print axioms Historical.Correspondence.repeated_unit_not_extra_support
#print axioms Historical.CorrespondenceInput.dataAccepted_iff
#print axioms Historical.CorrespondenceInput.accepted_data_recovers_row
#print axioms Historical.CorrespondenceInput.dossierAccepted_iff
